services:

  jobs:
    volumes:
      - ./scripts:/scripts

  dapytains:
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  qlever:
    ports:
      - "${PORT_QLEVER:-7011}:7001"

  qlever-ui:
    ports:
      - "${PORT_QLEVER_UI:-7012}:7000"